version: "3.9"
   
services:
  redis:
    image: redis
    restart: always

  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=django_webapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web_app:
    restart: always
    build:
      context: ./web_app
    command: [ "python3", "./blog_app_backend/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
