version: "3.9"
   
services:
  redis:
    image: redis
    restart: always

  celery-scheduler:
    restart: always
    build:
      context: ./web_app
    command: [ 'celery', '--workdir=./blog_app_backend', '-A', 'blog_app_backend', 'beat', '-l', 'DEBUG' ]
    depends_on:
      - db
      - redis

  worker:
    restart: always
    build:
      context: ./web_app
    command: [ 'celery', '--workdir=./blog_app_backend', '-A', 'blog_app_backend', 'worker' ]
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web_app:
    restart: always
    build:
      context: ./web_app
    command:
      sh -c "python ./blog_app_backend/manage.py migrate &&
             python ./blog_app_backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
