# Generated by Django 4.0.4 on 2022-05-15 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts', to='blogs_app.blogentity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'read_blogs',
            },
        ),
    ]
