# Generated by Django 4.0.4 on 2022-05-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0002_readblogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readblogs',
            options={'verbose_name_plural': 'Read blogs'},
        ),
        migrations.AddConstraint(
            model_name='readblogs',
            constraint=models.UniqueConstraint(fields=('user', 'blog'), name='unique_user_and_blog'),
        ),
    ]
